### ISSUE TITLE
Business Questions

### ISSUE THREAD

**Issue by tccao** [sohaibsyed21/572CookCounty#5]
Add business questions into project plan to discuss with sponsor by Monday, 06/12/2023.

**Comment by chriswco123** [comment]
Not exactly a business question but what is the "AdjustedAmountDue1_Org" column, I can't find the information in the excel sheet and it is different from "AdjustedAmountDue1" column.

**Comment by tccao** [comment]
> Not exactly a business question but what is the "AdjustedAmountDue1_Org" column, I can't find the information in the excel sheet and it is different from "AdjustedAmountDue1" column.

I have checked it myself and yeah, it's totally missing from the Excel sheet. You can put it in the project plan, section Business Question so we can ask the sponsor about it
